# Generated by Django 5.1.6 on 2025-03-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signoff',
            old_name='TA',
            new_name='instructor',
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='labs.qualitycriteria')),
                ('signoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='labs.signoff')),
            ],
            options={
                'unique_together': {('signoff', 'criteria')},
            },
        ),
    ]
