# Generated by Django 5.1.6 on 2025-03-01 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityscore',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
