# Generated by Django 5.1.6 on 2025-03-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_add_grade_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='has_challenges',
            field=models.BooleanField(default=False, help_text='Check if this part has challenge tasks'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.PositiveIntegerField(default=10, help_text='Maximum points for this challenge')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='labs.part')),
            ],
            options={
                'verbose_name_plural': 'Challenges',
                'ordering': ['part', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Earned points for this challenge')),
                ('comments', models.TextField(blank=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='labs.challenge')),
                ('signoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_scores', to='labs.signoff')),
            ],
            options={
                'unique_together': {('signoff', 'challenge')},
            },
        ),
    ]
