# Generated by Django 5.1.6 on 2025-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_part_has_challenges_challenge_challengescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text="Due date for this part's signoff", null=True),
        ),
    ]
